# permissions for end users to view nginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nginx-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: nginx-viewer-role
rules:
- apiGroups:
  - deploy.miit.ru
  resources:
  - nginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.miit.ru
  resources:
  - nginxes/status
  verbs:
  - get
